library(ggplot2)
library(dplyr)


get_statistics_df <- function(earnings, education_levels) {
  return(data.frame(
    earnings_mean=mean(earnings),
    earnings_median=median(earnings),
    earnings_std=ifelse(length(earnings) == 1, 0.0, sd(earnings)),
    earnings_iqr=IQR(earnings),
    bachelors_fraction=mean(education_levels >= 5)
  ))
}


get_prefix_df <- function(income_df, samples_df, prefix_trials) {
  prefix_df <- NULL
  for (i in prefix_trials) {
    earnings_slice <- samples_df[1:i, "earnings"]
    education_slice <- samples_df[1:i, "education_level"]
    prefix_df <- rbind(prefix_df, get_statistics_df(earnings_slice, education_slice))
  }
  prefix_df["trial"] <- prefix_trials
  return(prefix_df)
}


get_prefix_df_samples <- function(income_df, df_samples_count, sampling_func, prefix_trials) {
  prefix_df <- NULL
  for (i in 1:df_samples_count) {
    samples_df <- sampling_func(income_df)
    sample_prefix_df <- get_prefix_df(income_df, samples_df, prefix_trials)
    sample_prefix_df["sample_name"] <- paste("Sample", i)
    prefix_df <- rbind(prefix_df, sample_prefix_df)
  }
  return(prefix_df)
}


plot_trajectories <- function(df, column_name, title_suffix) {
  title <- paste("Trajectory of", column_name, title_suffix)
  print(ggplot(df, aes_string(x="trial", y=column_name, color="sample_name")) 
        + geom_line()
        + ggtitle(title)
        + theme(plot.title = element_text(hjust = 0.5, size=9)))
}


plot_samples_statistics <- function(income_df, sampling_func, title_suffix, prefix_trials) {
  prefix_df <- get_prefix_df_samples(income_df, df_samples_count=10, sampling_func, prefix_trials)
  for (column_name in colnames(prefix_df)) {
    if (column_name %in% c("trial", "sample_name")) {
      next
    }
    plot_trajectories(prefix_df, column_name, title_suffix)
  }
}


sample_uniformly <- function(income_df) {
  return(income_df[sample(nrow(income_df), size=1000, replace=FALSE), ])
}


sample_using_stratified_sampling <- function(income_df) {
  sector_stats <- (income_df %>% rename(sector=employment_sector)
                  %>% group_by(sector)
                  %>% summarize(count=length(sector)))
  sector_stats$weight <- 1 / (sector_stats$count / nrow(income_df))
  sector_stats$samples_weight <- 0.0
  sampled_df <- NULL
  for (i in 1:100) {
    min_samples_weight <- min(sector_stats$samples_weight)
    selected_row <- sector_stats[sector_stats$samples_weight == min_samples_weight, ][1, ]
    updated_samples_weight <- selected_row$samples_weight + selected_row$weight
    sector_stats[sector_stats$sector == selected_row$sector, ]$samples_weight <- updated_samples_weight
    selected_sector_df <- filter(income_df, employment_sector == selected_row$sector)
    sampled_df <- rbind(sampled_df, selected_sector_df[sample(nrow(selected_sector_df), size=1), ])
  }
  return(sampled_df)
}


income_df <- read.table(
  "http://www.math.uni.wroc.pl/~elsner/dydaktyka/dane/income.dat",
  col.names=c("id", "age", "education_level", "sex", "earnings", "employment_sector")
)
print(get_statistics_df(income_df$earnings, income_df$education_level))
plot_samples_statistics(income_df,
                        sampling_func=sample_uniformly,
                        title_suffix="(from 1000 randomly chosen samples)",
                        prefix_trials=seq(1, 1000))
plot_samples_statistics(income_df,
                        sampling_func=sample_using_stratified_sampling,
                        title_suffix="(from 100 samples chosen using stratified sampling)",
                        prefix_trials=seq(1, 100, 10))
rm(list = ls())

"
The results of experiments show that all of the examined statistics converge to values of the true
distribution. After 1000 trials, mean of earnings is (with very high probability) in the
range [35000, 40000] (the true mean is 37864), median is in the range [28000, 32000] (the 
true median is 29717), standard deviation is in the range [30000, 40000] (the true standard
deviation is 36158), IQR is in the range [26000, 32000] (the true IQR is 29503), fraction of people
with bachelor's degree is in the range [0.28, 0.32]. This would suggest that for this distribution,
standard deviation converges most slowly to its true value.

Experiments also show the convergence of statistics of 100 samples generated by stratified sampling. These
100 samples always contain 73 people in the private sector (sector 5), 17 people in the public sector
(sector 6) and 10 self-employed people (sector 7). It can be seen that statistics converge faster to their
true values as their value after 100 trials is closer to true values, comparig to the previous experiment.
For instance, in the previous experiment, means were in the range [30000, 48000] after 100 trials, but
in this experiment, they were in the range [35000, 45000]. It can be also seen that statistics didn't
converge as close to the true values as after 1000 trials in the previous experiment.
"